spring.application.name=msa
spring.datasource.url=jdbc:mysql://localhost:3306/msa
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jackson.deserialization.adjust-dates-to-context-time-zone=false

spring.quartz.job-store-type=jdbc
spring.quartz.properties.org.quartz.scheduler.instanceName=MyScheduler
spring.quartz.properties.org.quartz.scheduler.instanceId=AUTO
spring.quartz.properties.org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
spring.quartz.properties.org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate
spring.quartz.properties.org.quartz.jobStore.misfireThreshold=60000
spring.quartz.jdbc.initialize-schema=always

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anhquan20102003@gmail.com
spring.mail.password=gofrptljwgjptmmg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=1081
server.servlet.context-path=/msa/api

jwt.signerKey=FH7jrUqilRiuOZJnYs!B49FiV3BRG2EKW/xrC!BvuIHeQdy6fmnw3bZD3c2GycRDqbUYgL-Z4L6rkKMU8FrQzaLvzKQFOSZmhss2?37HqiCozilTgcQd-/iqfpQGwMLZ!OjQ-O8jVfhf73CxoPDR2bhg2LWIHluwxt293ezeX/Zc0ijLJyTCBIO!-QjdBlryikLZYxzzHj/gwz8-vguokfXzpQPJbw8e8VYfLTThTlqj8plRVm1BeuPzRJgDWsy?
jwt.valid-duration=3600
jwt.refreshable-duration=36000

shippo.apikey=shippo_test_ecd9f00cb3e0d0b284e7f1cff2d3a76d1471826f
shippo.url=https://api.goshippo.com/shipments

zero-bounce.api.key=5497d5ce12ee486da7951f94d381b2c4