spring:
  application:
    name: msa
  datasource:
    url: jdbc:mysql://localhost:3306/msa_1
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: false
  data:
    redis:
      host: redis
      port: 6379
      password: 
      database: 0
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: true

  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            misfireThreshold: 60000
    jdbc:
      initialize-schema: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: anhquan20102003@gmail.com
    password: gofrptljwgjptmmg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 1081
  servlet:
    context-path: /msa/api

jwt:
  signerKey: FH7jrUqilRiuOZJnYs!B49FiV3BRG2EKW/xrC!BvuIHeQdy6fmnw3bZD3c2GycRDqbUYgL-Z4L6rkKMU8FrQzaLvzKQFOSZmhss2?37HqiCozilTgcQd-/iqfpQGwMLZ!OjQ-O8jVfhf73CxoPDR2bhg2LWIHluwxt293ezeX/Zc0ijLJyTCBIO!-QjdBlryikLZYxzzHj/gwz8-vguokfXzpQPJbw8e8VYfLTThTlqj8plRVm1BeuPzRJgDWsy?
  valid-duration: 3600
  refreshable-duration: 36000

shippo:
  apikey: shippo_test_ecd9f00cb3e0d0b284e7f1cff2d3a76d1471826f
  url: https://api.goshippo.com/shipments

zero-bounce:
  api:
    key: 5497d5ce12ee486da7951f94d381b2c4
